Document: jdarkroom
Title: Debian jdarkroom Manual
Author: <insert document author here>
Abstract: This manual describes what jdarkroom is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/jdarkroom/jdarkroom.sgml.gz

Format: postscript
Files: /usr/share/doc/jdarkroom/jdarkroom.ps.gz

Format: text
Files: /usr/share/doc/jdarkroom/jdarkroom.text.gz

Format: HTML
Index: /usr/share/doc/jdarkroom/html/index.html
Files: /usr/share/doc/jdarkroom/html/*.html
